config/routes.rb
Rails.application.routes.draw do
  resources :territories
  resources :suppliers
  resources :shippers
  resources :regions
  resources :products
  resources :orders
  resources :employees
  resources :employee_territories
  resources :customers
  resources :customer_demographics
  resources :customer_customer_demos
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/customer_demographic.rb
class CustomerDemographic < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/employee_territory.rb
class EmployeeTerritory < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
end

app/models/shipper.rb
class Shipper < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/territory.rb
class Territory < ActiveRecord::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:LastName, :FirstName, :Title, :TitleOfCourtesy, :BirthDate, :HireDate, :Address, :City, :Region, :PostalCode, :Country, :HomePhone, :Extension, :Photo, :Notes, :ReportsTo, :PhotoPath)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:CustomerID, :EmployeeID, :OrderDate, :RequiredDate, :ShippedDate, :ShipVia, :Freight, :ShipName, :ShipAddress, :ShipCity, :ShipRegion, :ShipPostalCode, :ShipCountry)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/shippers_helper.rb
module ShippersHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/territories_helper.rb
module TerritoriesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :LastName %><br>
    <%= f.text_area :LastName %>
  </div>
  <div class="field">
    <%= f.label :FirstName %><br>
    <%= f.text_area :FirstName %>
  </div>
  <div class="field">
    <%= f.label :Title %><br>
    <%= f.text_area :Title %>
  </div>
  <div class="field">
    <%= f.label :TitleOfCourtesy %><br>
    <%= f.text_area :TitleOfCourtesy %>
  </div>
  <div class="field">
    <%= f.label :BirthDate %><br>
    <%= f.date_select :BirthDate %>
  </div>
  <div class="field">
    <%= f.label :HireDate %><br>
    <%= f.date_select :HireDate %>
  </div>
  <div class="field">
    <%= f.label :Address %><br>
    <%= f.text_area :Address %>
  </div>
  <div class="field">
    <%= f.label :City %><br>
    <%= f.text_area :City %>
  </div>
  <div class="field">
    <%= f.label :Region %><br>
    <%= f.text_area :Region %>
  </div>
  <div class="field">
    <%= f.label :PostalCode %><br>
    <%= f.text_area :PostalCode %>
  </div>
  <div class="field">
    <%= f.label :Country %><br>
    <%= f.text_area :Country %>
  </div>
  <div class="field">
    <%= f.label :HomePhone %><br>
    <%= f.text_area :HomePhone %>
  </div>
  <div class="field">
    <%= f.label :Extension %><br>
    <%= f.text_area :Extension %>
  </div>
  <div class="field">
    <%= f.label :Photo %><br>
    <%= f.text_field :Photo %>
  </div>
  <div class="field">
    <%= f.label :Notes %><br>
    <%= f.text_area :Notes %>
  </div>
  <div class="field">
    <%= f.label :ReportsTo %><br>
    <%= f.number_field :ReportsTo %>
  </div>
  <div class="field">
    <%= f.label :PhotoPath %><br>
    <%= f.text_area :PhotoPath %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Lastname</th>
      <th>Firstname</th>
      <th>Title</th>
      <th>Titleofcourtesy</th>
      <th>Birthdate</th>
      <th>Hiredate</th>
      <th>Address</th>
      <th>City</th>
      <th>Region</th>
      <th>Postalcode</th>
      <th>Country</th>
      <th>Homephone</th>
      <th>Extension</th>
      <th>Photo</th>
      <th>Notes</th>
      <th>Reportsto</th>
      <th>Photopath</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.LastName %></td>
        <td><%= employee.FirstName %></td>
        <td><%= employee.Title %></td>
        <td><%= employee.TitleOfCourtesy %></td>
        <td><%= employee.BirthDate %></td>
        <td><%= employee.HireDate %></td>
        <td><%= employee.Address %></td>
        <td><%= employee.City %></td>
        <td><%= employee.Region %></td>
        <td><%= employee.PostalCode %></td>
        <td><%= employee.Country %></td>
        <td><%= employee.HomePhone %></td>
        <td><%= employee.Extension %></td>
        <td><%= employee.Photo %></td>
        <td><%= employee.Notes %></td>
        <td><%= employee.ReportsTo %></td>
        <td><%= employee.PhotoPath %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.LastName %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @employee.FirstName %>
</p>

<p>
  <strong>Title:</strong>
  <%= @employee.Title %>
</p>

<p>
  <strong>Titleofcourtesy:</strong>
  <%= @employee.TitleOfCourtesy %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @employee.BirthDate %>
</p>

<p>
  <strong>Hiredate:</strong>
  <%= @employee.HireDate %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.Address %>
</p>

<p>
  <strong>City:</strong>
  <%= @employee.City %>
</p>

<p>
  <strong>Region:</strong>
  <%= @employee.Region %>
</p>

<p>
  <strong>Postalcode:</strong>
  <%= @employee.PostalCode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @employee.Country %>
</p>

<p>
  <strong>Homephone:</strong>
  <%= @employee.HomePhone %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @employee.Extension %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @employee.Photo %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @employee.Notes %>
</p>

<p>
  <strong>Reportsto:</strong>
  <%= @employee.ReportsTo %>
</p>

<p>
  <strong>Photopath:</strong>
  <%= @employee.PhotoPath %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>