config/routes.rb
Rails.application.routes.draw do
  resources :territories
  resources :suppliers
  resources :shippers
  resources :regions
  resources :products
  resources :orders
  resources :employees
  resources :employee_territories
  resources :customers
  resources :customer_demographics
  resources :customer_customer_demos
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/customer_demographic.rb
class CustomerDemographic < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/employee_territory.rb
class EmployeeTerritory < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
end

app/models/shipper.rb
class Shipper < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/territory.rb
class Territory < ActiveRecord::Base
end

app/controllers/employee_territories_controller.rb
class EmployeeTerritoriesController < ApplicationController
  before_action :set_employee_territory, only: [:show, :edit, :update, :destroy]

  # GET /employee_territories
  # GET /employee_territories.json
  def index
    @employee_territories = EmployeeTerritory.all
  end

  # GET /employee_territories/1
  # GET /employee_territories/1.json
  def show
  end

  # GET /employee_territories/new
  def new
    @employee_territory = EmployeeTerritory.new
  end

  # GET /employee_territories/1/edit
  def edit
  end

  # POST /employee_territories
  # POST /employee_territories.json
  def create
    @employee_territory = EmployeeTerritory.new(employee_territory_params)

    respond_to do |format|
      if @employee_territory.save
        format.html { redirect_to @employee_territory, notice: 'Employee territory was successfully created.' }
        format.json { render :show, status: :created, location: @employee_territory }
      else
        format.html { render :new }
        format.json { render json: @employee_territory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_territories/1
  # PATCH/PUT /employee_territories/1.json
  def update
    respond_to do |format|
      if @employee_territory.update(employee_territory_params)
        format.html { redirect_to @employee_territory, notice: 'Employee territory was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_territory }
      else
        format.html { render :edit }
        format.json { render json: @employee_territory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_territories/1
  # DELETE /employee_territories/1.json
  def destroy
    @employee_territory.destroy
    respond_to do |format|
      format.html { redirect_to employee_territories_url, notice: 'Employee territory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_territory
      @employee_territory = EmployeeTerritory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_territory_params
      params.require(:employee_territory).permit(:EmployeeID, :TerritoryID)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employee_territories_helper.rb
module EmployeeTerritoriesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/shippers_helper.rb
module ShippersHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/territories_helper.rb
module TerritoriesHelper
end

app/views/employee_territories/_form.html.erb
<%= form_for(@employee_territory) do |f| %>
  <% if @employee_territory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee_territory.errors.count, "error") %> prohibited this employee_territory from being saved:</h2>

      <ul>
      <% @employee_territory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :EmployeeID %><br>
    <%= f.number_field :EmployeeID %>
  </div>
  <div class="field">
    <%= f.label :TerritoryID %><br>
    <%= f.text_area :TerritoryID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employee_territories/edit.html.erb
<h1>Editing Employee Territory</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee_territory %> |
<%= link_to 'Back', employee_territories_path %>

app/views/employee_territories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employee Territories</h1>

<table>
  <thead>
    <tr>
      <th>Employeeid</th>
      <th>Territoryid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_territories.each do |employee_territory| %>
      <tr>
        <td><%= employee_territory.EmployeeID %></td>
        <td><%= employee_territory.TerritoryID %></td>
        <td><%= link_to 'Show', employee_territory %></td>
        <td><%= link_to 'Edit', edit_employee_territory_path(employee_territory) %></td>
        <td><%= link_to 'Destroy', employee_territory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee territory', new_employee_territory_path %>

app/views/employee_territories/new.html.erb
<h1>New Employee Territory</h1>

<%= render 'form' %>

<%= link_to 'Back', employee_territories_path %>

app/views/employee_territories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employeeid:</strong>
  <%= @employee_territory.EmployeeID %>
</p>

<p>
  <strong>Territoryid:</strong>
  <%= @employee_territory.TerritoryID %>
</p>

<%= link_to 'Edit', edit_employee_territory_path(@employee_territory) %> |
<%= link_to 'Back', employee_territories_path %>